import type { Metadata } from "next";
import "./globals.css";
import ScreenCheck from "@/components/screen-check";

export const metadata: Metadata = {
  title: "Buziak",
  description: "Generated by create next app",
  icons: "/buziak.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
      >
        <ScreenCheck>
          {children}
        </ScreenCheck>
      </body>
    </html>
  );
}
